container_opts:
  image: datadog/apigentools:1.6.6
languages:
  go:
    generation:
      default:
        commands:
          - commandline:
            - function: openapi_generator_generate
            - --type-mappings
            - object=interface{}
            description: Generate go code using openapi-generator
          - commandline:
            - cp
            - -rfvp
            - "{{version_output_dir}}/../../assets/shared/."
            - "{{version_output_dir}}"
            description: Copy shared assets in the generated folder
        templates:
          source:
            type: openapi-git
            git_committish: "v7.0.0" # git committish to checkout before extracting the templates
            templates_dir: go # directory with templates for this language
            system: true
    downstream_templates:
      downstream-templates/go/README.md: README.md
    github_org_name: arduino
    github_repo_name: iot-client-go
    library_version: '1.3.5'
    spec_versions:
      - v2
    version_path_template: ''
  html2:
    generation:
      default:
        commands:
          - commandline:
            - function: openapi_generator_generate
            description: Generate doc using openapi-generator
        templates:
          patches:
            - template-patches/html2-arduino-css.patch
            - template-patches/html2-index.patch
            - template-patches/html2-sample-js.patch
          source:
            type: openapi-git
            git_committish: "v7.0.0" # git committish to checkout before extracting the templates
            templates_dir: htmlDocs2 # directory with templates for this language
            system: true
    github_org_name: arduino
    github_repo_name: iot-client-docs
    library_version: '1.3.5'
    spec_versions:
      - v2
    version_path_template: ''
  javascript:
    generation:
      default:
        commands:
          - commandline:
            - function: openapi_generator_generate
            - --type-mappings
            - AnyType=Object
            description: Generate js code using openapi-generator
          - commandline:
            - cp
            - -rfvp
            - "{{version_output_dir}}/../../assets/shared/."
            - "{{version_output_dir}}"
            description: Copy shared assets in the generated folder
        templates:
          patches:
            - template-patches/javascript-api-client.patch
          source:
            type: openapi-git
            git_committish: "v7.0.0" # git committish to checkout before extracting the templates
            templates_dir: Javascript # directory with templates for this language
            system: true
    downstream_templates:
      downstream-templates/javascript/README.md: README.md
    github_org_name: arduino
    github_repo_name: iot-client-js
    library_version: '1.3.5'
    spec_versions:
      - v2
    version_path_template: ''
  python:
    generation:
      default:
        commands:
          - commandline:
            - function: openapi_generator_generate
            description: Generate py code using openapi-generator
          - commandline:
            - cp
            - -rfvp
            - "{{version_output_dir}}/../../assets/shared/."
            - "{{version_output_dir}}"
            description: Copy shared assets in the generated folder
        templates:
          source:
            type: openapi-git
            git_committish: "v7.0.0" # git committish to checkout before extracting the templates
            templates_dir: python # directory with templates for this language
            system: true
    downstream_templates:
      downstream-templates/python/README.md: README.md
      downstream-templates/python/setup.py: setup.py
    github_org_name: arduino
    github_repo_name: iot-client-py
    library_version: '1.3.5'
    spec_versions:
      - v2
    version_path_template: ''
spec_sections:
  v2:
    - swagger.yaml
    - header.yaml
    - shared.yaml
spec_versions:
  - v2
