name: generate

on:
  pull_request:
  push:
    tags:
      - 'v[0-9].*'

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
          architecture: 'x64'

      - name: Install apigentools
        run: pip install apigentools

      - name: Validate specfile
        run: apigentools validate

      - name: Generate clients
        env:
          APIGENTOOLS_GIT_VIA_HTTPS: true
          APIGENTOOLS_GIT_VIA_HTTPS_OAUTH_TOKEN: ${{ secrets.GH_PUSH_TOKEN }}
        run: apigentools generate --clone-repo

      - name: Align permissions of generated code
        run: |
          chown -R ${USER}:${USER} generated

      - name: Push client repos
        if: github.event_name == 'push'
        env:
          APIGENTOOLS_GIT_VIA_HTTPS: true
          APIGENTOOLS_GIT_VIA_HTTPS_OAUTH_TOKEN: ${{ secrets.GH_PUSH_TOKEN }}
        run: |
          rm -rf generated/iot-client-js/docs/
          git config --global user.email "arduinobot@arduino.cc"
          git config --global user.name "ArduinoBot"
          apigentools push
