name: generate

on:
  push:
    tags:
      - '[0-9].[0-9]'

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup Node
        uses: actions/setup-node@v1

      - name: Install Openapi Generator
        run: npm install @openapitools/openapi-generator-cli -g

      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
          architecture: 'x64'

      - name: Install apigentools
        # use master until 0.3.0 is released
        run: pip install git+https://github.com/DataDog/apigentools.git@master

      - name: Generate clients
        env:
          APIGENTOOLS_GIT_VIA_HTTPS: true
          APIGENTOOLS_GIT_VIA_HTTPS_OAUTH_TOKEN: ${{ secrets.GH_PUSH_TOKEN }}
        run: apigentools generate --builtin-templates --clone-repo

      - name: Push client repos
        env:
          APIGENTOOLS_GIT_VIA_HTTPS: true
          APIGENTOOLS_GIT_VIA_HTTPS_OAUTH_TOKEN: ${{ secrets.GH_PUSH_TOKEN }}
        run: |
          git config --global user.email "arduinobot@arduino.cc"
          git config --global user.name "ArduinoBot"
          apigentools push
