name: generate

env:
  GO_VERSION: "1.23"

on:
  pull_request:
  push:
    tags:
      - 'v[0-9].*'

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'
          architecture: 'x64'

      - name: Install apigentools
        run: pip install apigentools==1.1.0 # NB: If changes are needed, remeber to update the docker image accordingly at config/config.yaml 

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Merge openAPI specs
        run: |
          cd openapi-merger && go run main.go && cd ..

      - name: Validate specfile
        run: apigentools validate

      - name: Generate clients
        env:
          APIGENTOOLS_GIT_VIA_HTTPS: true
          APIGENTOOLS_GIT_VIA_HTTPS_OAUTH_TOKEN: ${{ secrets.GH_PUSH_TOKEN }}
        run: apigentools generate --clone-repo

      - name: Align permissions of generated code
        run: |
          sudo chown -R ${USER}:${USER} generated

      - name: Push client repos
        if: github.event_name == 'push'
        env:
          APIGENTOOLS_GIT_VIA_HTTPS: true
          APIGENTOOLS_GIT_VIA_HTTPS_OAUTH_TOKEN: ${{ secrets.GH_PUSH_TOKEN }}
        run: |
          rm -rf generated/iot-client-js/docs/
          rm -rf generated/iot-client-js/test/
          git config --global user.email "arduinobot@arduino.cc"
          git config --global user.name "ArduinoBot"
          apigentools push
