name: test

on: pull_request

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup Node
        uses: actions/setup-node@v1

      - name: Install Openapi Generator
        run: npm install @openapitools/openapi-generator-cli -g

      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
          architecture: 'x64'

      - name: Install apigentools
        # use master until 0.3.0 is released
        run: pip install git+https://github.com/DataDog/apigentools.git@master

      - name: Validate specfile
        run: apigentools validate

      - name: Generate clients
        run: apigentools generate --builtin-templates
